# Load Libraries
```{r}
library(tidyverse)
library(showtext)
library(stringr)
library(ggradar)
library(MetBrewer)
library(cowplot)
```
# Get data
```{r}
breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv') %>%
  mutate(Breed = str_squish(Breed)) %>% .[, c(1:5, 7, 10:16)]
breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv') %>%
  mutate(Breed = str_squish(Breed)) %>% select(Breed, `2020 Rank`)
```
# Load Fonts
```{r}
font_add_google("Quicksand")
font_add_google("Fira Sans Condensed")
showtext_auto()
```
# Wrangle
```{r}
breed_rank <- breed_traits %>% 
  left_join(breed_rank_all, by="Breed") %>%
  filter(`2020 Rank` <= 3) %>% 
  select(-`2020 Rank`) %>% 
  pivot_longer(-Breed) %>% 
  group_by(Breed) %>% 
  mutate(Breed=str_squish(Breed),
         name=case_when(name=="Affectionate With Family"~"Family Affection",
                        name=="Good With Young Children"~"Child Friendly",
                        name=="Good With Other Dogs"~"Dog Friendly",
                        name=="Openness To Strangers"~"Strangers Friendly",
                        name=="Watchdog/Protective Nature"~"Protective",
                        TRUE~name),
         name=str_remove(name,"Level")) %>% 
    
  ungroup() %>% 
  pivot_wider(names_from=name) %>% 
  mutate(Breed=factor(Breed,levels=Breed))        
```
# Plot
```{r}
main <- breed_rank %>% ggradar(grid.max=5,grid.min=1,grid.mid=3,
                       values.radar=c("1","3","5"),
                       font.radar = "Quicksand",
                       gridline.mid.colour = "gray",
                       gridline.max.linetype="9f",
                       #gridline.mid.linetype = "5f",
                       grid.label.size = 10,
                       axis.label.size=11.5,
                       gridline.label.offset=0.5,
                       axis.label.offset = 1.1,
                       group.line.width=0.8,
                       group.point.size=1.2,
                       group.colours=met.brewer("NewKingdom", 3),
                       background.circle.colour="#fbf7f0",
                       grid.line.width = 0.5
                       )+
  facet_wrap(vars(group),nrow=3)+
  theme_void()+
  theme(legend.position="none",
        strip.text.x=element_blank(),
        plot.margin=margin(3, -5, 2, 10,unit="cm"),
        panel.spacing.y = unit(2,"cm"))
final <- ggdraw(main)+
  theme(plot.background = element_rect(fill="#fbf7f0", color="#fbf7f0"),
        plot.margin = margin(1, 0, -1, 0, "cm"),
        )+
  draw_text("Top 3 popular dog breeds of US in 2020",x=0.035,y=0.99,family="Fira Sans Condensed", size=150,fontface="bold",color=met.brewer("NewKingdom",4)[4], hjust=0)+
  draw_text("Retrievers (Labrador)",x=0.035,y=0.91,family="Fira Sans Condensed", size=80,fontface="bold",color=met.brewer("NewKingdom",3)[1], hjust=0)+
  draw_image("lab.png",x=-0.15,y=0.25,scale=0.25)+
  draw_text("French Bulldogs",x=0.035,y=0.62,family="Fira Sans Condensed", size=80,fontface="bold",color=met.brewer("NewKingdom",3)[2], hjust=0)+
  draw_image("bull.png",x=-0.15,y=0,scale=0.3)+
  draw_text("German Shepherd",x=0.035,y=0.32,family="Fira Sans Condensed", size=80,fontface="bold",color=met.brewer("NewKingdom",3)[3], hjust=0) +
  draw_image("shepherd.png",x=-0.15,y=-0.3,scale=0.35)+
  draw_text("Viz: Nischal Karki | Data: American Kennel Club",x=0.035,y=0.05,family="Fira Sans Condensed",color="gray",hjust=0,size=50)
ggsave("DogBreeds.png",plot=final,width=12,height=14)
```
